service: default
runtime: python39

basic_scaling:
    max_instances: 5
    idle_timeout: 10m

resources:
    cpu: 4
    memory_gb: 8
    disk_size_gb: 10

entrypoint: gunicorn -b 0.0.0.0:7080 main:server